# Generated by Django 5.2.1 on 2025-05-29 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('flag_url', models.URLField(blank=True, help_text='URL to country flag image')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('court_type', models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor'), ('COVERED_OUTDOOR', 'Covered Outdoor')], default='INDOOR', max_length=20)),
                ('surface_type', models.CharField(choices=[('WOOD', 'Wooden'), ('SYNTHETIC', 'Synthetic'), ('CONCRETE', 'Concrete'), ('OTHER', 'Other')], default='WOOD', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['venue', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='match.country')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField()),
                ('priority', models.IntegerField(default=0, help_text='Higher priority sponsors appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='match.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('total_courts', models.PositiveIntegerField(default=1)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_cafeteria', models.BooleanField(default=False)),
                ('has_livestream', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='match.country')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, help_text='Start date for this venue in the tournament', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for this venue in the tournament', null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_venues', to='match.tournament')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_venues', to='match.venue')),
            ],
            options={
                'verbose_name': 'Tournament Venue',
                'verbose_name_plural': 'Tournament Venues',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='venues',
            field=models.ManyToManyField(blank=True, related_name='tournaments', through='match.TournamentVenue', to='match.venue'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLES', 'Doubles'), ('MIXED_DOUBLES', 'Mixed Doubles')], max_length=20)),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Completed', 'Completed'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=20)),
                ('current_game', models.IntegerField(default=1)),
                ('team1_sets', models.IntegerField(default=0)),
                ('team2_sets', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='match.court')),
                ('player1_team1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_player1_team1', to='match.player')),
                ('player1_team2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_player1_team2', to='match.player')),
                ('player2_team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player2_team1', to='match.player')),
                ('player2_team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player2_team2', to='match.player')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serving_matches', to='match.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='match.tournament')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='match.venue')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.AddField(
            model_name='court',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='match.venue'),
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField(help_text='The sequential number of the game (e.g., 1 for Game 1, 2 for Game 2).')),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('match', models.ForeignKey(help_text='The match this game score belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to='match.match')),
            ],
            options={
                'verbose_name': 'Game Score',
                'verbose_name_plural': 'Game Scores',
                'ordering': ['match', 'game_number'],
                'unique_together': {('match', 'game_number')},
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], name='match_playe_name_2e23ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsor',
            unique_together={('name', 'tournament')},
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['city'], name='match_venue_city_e2b0b7_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['country'], name='match_venue_country_6e6361_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('name', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamentvenue',
            unique_together={('tournament', 'venue')},
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['name'], name='match_tourn_name_c71a62_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'scheduled_time'], name='match_match_tournam_5df7a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tournament', 'player1_team1', 'player1_team2', 'scheduled_time'), name='unique_match'),
        ),
        migrations.AlterUniqueTogether(
            name='court',
            unique_together={('venue', 'name')},
        ),
    ]
