# Generated by Django 5.2.1 on 2025-11-12 07:47

import match.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload player photo (optional)', null=True, upload_to=match.models.player_photo_path),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload sponsor logo (optional)', null=True, upload_to=match.models.sponsor_logo_path),
        ),
    ]
