# Generated by Django 5.2.1 on 2026-04-30 12:50

import django.db.models.deletion
import match.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_match_umpire_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to='match.match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpire_pin',
            field=models.CharField(default=match.models.generate_pin, help_text='4-digit PIN for umpire access. Set in admin before match day.', max_length=4),
        ),
        migrations.AlterField(
            model_name='tournamentvenue',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentvenue',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
