# Generated by Django 5.2.1 on 2026-05-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_tournament_events'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournamentevent',
            name='unique_event_name_per_tournament',
        ),
        migrations.AlterField(
            model_name='tournamentevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentevent',
            unique_together={('tournament', 'name')},
        ),
    ]
