# Generated by Django 5.2.1 on 2026-05-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_eventregistration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventregistration',
            name='unique_player_per_event',
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'player')},
        ),
    ]
