# Generated by Django 5.2.1 on 2026-05-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_remove_eventregistration_unique_player_per_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_teams', to='match.tournamentevent')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_teams_as_player1', to='match.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_teams_as_player2', to='match.player')),
            ],
            options={
                'ordering': ['event', 'name'],
                'unique_together': {('event', 'player1', 'player2')},
            },
        ),
    ]
