# Generated by Django 5.2.1 on 2026-05-05 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_doublesteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='BracketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField()),
                ('feeds_as_slot', models.PositiveSmallIntegerField(blank=True, help_text='1 = winner fills entry1 of feeds_into, 2 = fills entry2', null=True)),
                ('is_bye', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_slots_as_entry1', to='match.doublesteam')),
                ('entry1_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_slots_as_entry1', to='match.player')),
                ('entry2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_slots_as_entry2', to='match.doublesteam')),
                ('entry2_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_slots_as_entry2', to='match.player')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracket_matches', to='match.tournamentevent')),
                ('feeds_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fed_by', to='match.bracketmatch')),
                ('match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_slot', to='match.match')),
                ('winner_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_wins', to='match.doublesteam')),
                ('winner_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bracket_wins', to='match.player')),
            ],
            options={
                'ordering': ['round_number', 'position'],
                'unique_together': {('event', 'round_number', 'position')},
            },
        ),
    ]
