# Generated by Django 5.2.1 on 2026-05-06 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_match_assigned_umpire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='assigned_umpire',
            field=models.ForeignKey(blank=True, help_text='Umpire assigned by the director.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
