# Generated by Django 5.2.1 on 2026-05-11 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_court_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier used for screen URLs (/screen/court/<slug>). Auto-generated from venue + court name if left blank.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_matches', to='match.tournamentevent'),
        ),
        migrations.CreateModel(
            name='DoublesCourtState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_team', models.IntegerField(choices=[(1, 'Team 1'), (2, 'Team 2')], help_text='Which team currently holds service')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='court_state', to='match.match')),
                ('receiver', models.ForeignKey(help_text='Player currently receiving', on_delete=django.db.models.deletion.PROTECT, related_name='court_state_receiving', to='match.player')),
                ('server', models.ForeignKey(help_text='Player currently serving', on_delete=django.db.models.deletion.PROTECT, related_name='court_state_serving', to='match.player')),
                ('team1_left', models.ForeignKey(help_text='Team 1 player currently in the LEFT service court', on_delete=django.db.models.deletion.PROTECT, related_name='court_state_t1_left', to='match.player')),
                ('team1_right', models.ForeignKey(help_text='Team 1 player currently in the RIGHT service court', on_delete=django.db.models.deletion.PROTECT, related_name='court_state_t1_right', to='match.player')),
                ('team2_left', models.ForeignKey(help_text='Team 2 player currently in the LEFT service court', on_delete=django.db.models.deletion.PROTECT, related_name='court_state_t2_left', to='match.player')),
                ('team2_right', models.ForeignKey(help_text='Team 2 player currently in the RIGHT service court', on_delete=django.db.models.deletion.PROTECT, related_name='court_state_t2_right', to='match.player')),
            ],
            options={
                'verbose_name': 'Doubles Court State',
                'verbose_name_plural': 'Doubles Court States',
            },
        ),
    ]
